/**
 * 重试一个promise 传入的参数应该是生成promise的方法 () => promise
 * 1. 如果正常返回, 返回结果
 * 2. 如果异常, 重试times次
 * 3. 重试过程中如果正常返回, 返回结果
 * 4. 如果全部重试都失败, 抛出异常
 *
 * @param promise: () => promise
 * @param times: 重试次数
 * @returns {Promise.<*>}
 */
export default async function retry({ promise, times = 3 }) {
  const errCount = times - 1
  try {
    return await promise()
  } catch (e) {
    if (errCount >= 0) {
      return await retry({ promise, times: errCount })
    }
    throw e
  }
}
